--------------------------------------------------------
--  DDL for Table MELANBIDE11_CONTRATACION
--------------------------------------------------------
  CREATE TABLE MELANBIDE11_CONTRATACION 
   (	ID NUMBER(8,0), 
	NUM_EXP VARCHAR2(30 BYTE), 
	NOFECONT VARCHAR2(20 BYTE), 
	IDCONT1 VARCHAR2(20 BYTE), 
	IDCONT2 VARCHAR2(20 BYTE), 
	DNICONT VARCHAR2(15 BYTE), 
	NOMCONT VARCHAR2(100 BYTE), 
	APE1CONT VARCHAR2(50 BYTE), 
	APE2CONT VARCHAR2(50 BYTE), 
	FECHNACCONT DATE, 
	EDADCONT NUMBER(2,0), 
	SEXOCONT VARCHAR2(1 BYTE), 
	MAY55CONT VARCHAR2(1 BYTE), 
	ACCFORCONT VARCHAR2(1 BYTE), 
	CODFORCONT VARCHAR2(20 BYTE), 
	DENFORCONT VARCHAR2(150 BYTE),
	PUESTOCONT VARCHAR2(100 BYTE), 
	OCUCONT VARCHAR2(150 BYTE),
	CODOCUCONT VARCHAR2(8 BYTE), 	
	DESTITULACION VARCHAR2(200 BYTE),
	TITULACION VARCHAR2(12 BYTE),
	CPROFESIONALIDAD VARCHAR2(10 BYTE), 
	MODCONT VARCHAR2(100 BYTE), 
	JORCONT VARCHAR2(4 BYTE), 
	PORCJOR NUMBER(5,2), 
	HORASCONV NUMBER(4,0), 
	FECHINICONT DATE, 
	FECHFINCONT DATE, 
	DURCONT VARCHAR2(6 BYTE), 
	GRSS VARCHAR2(2 BYTE), 
	DIRCENTRCONT VARCHAR2(100 BYTE), 
	NSSCONT VARCHAR2(22 BYTE), 
	CSTCONT NUMBER(8,2), 
	TIPRSB VARCHAR2(1 BYTE),
	IMPSUBVCONT NUMBER(8,2) 	
) ;

	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.ID IS 'Id secuencial';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.NUM_EXP IS 'Número de Expediente';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.NOFECONT IS 'Número de Oferta';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.IDCONT1 IS 'Id. de contrato de oferta';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.IDCONT2 IS 'Id. de contrato directo';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DNICONT IS 'DNI/NIE';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.NOMCONT IS 'Nombre';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.APE1CONT IS 'Apellido 1';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.APE2CONT IS 'Apellido 2';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.FECHNACCONT IS 'Fecha Nacimiento';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.EDADCONT IS 'Edad';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.SEXOCONT IS 'Sexo';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.MAY55CONT is '¿Mayor de 55 años?';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.ACCFORCONT  IS '¿Finaliza en 2021/2022 acción formativa?';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.CODFORCONT IS 'Código de la acción formativa finalizada';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DENFORCONT IS 'Denominación de la acción formativa finalizada';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.PUESTOCONT IS 'Nombre del puesto';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.CODOCUCONT  IS 'Código de ocupación';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.OCUCONT 	 IS 'Nombre de ocupación';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DESTITULACION IS 'Titulación solicitud';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.TITULACION  IS 'Titulación';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.CPROFESIONALIDAD  IS 'Cert.Profesionalidad';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.MODCONT  IS 'Modalidad de contrato';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.JORCONT  IS 'Jornada: Completa ó Parcial';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.PORCJOR  IS 'Porcentaje de Jornada Parcial';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.HORASCONV IS 'Horas convenio (en caso de Jornada Parcial)';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.FECHINICONT  IS 'Fecha inicio del contrato';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.FECHFINCONT IS 'Fecha fin del contrato prevista';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DURCONT IS 'Duración del contrato: en meses';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.GRSS  IS 'Grupo de cotización de la S.S.';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.DIRCENTRCONT IS 'Dirección de centro de trabajo';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.NSSCONT IS 'Número de cotización de la S.S.';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.CSTCONT IS 'Coste contrato';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.TIPRSB IS 'Tipo de retribución salarial bruta (coste contrato) A/M';
	COMMENT ON COLUMN MELANBIDE11_CONTRATACION.IMPSUBVCONT IS 'Importe de la Subvención solicitada';
	
--------------------------------------------------------
--  DDL for Index MELANBIDE11_CONTRATACION_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX MELANBIDE11_CONTRATACION_PK ON MELANBIDE11_CONTRATACION (ID);

--------------------------------------------------------
--  Constraints for Table MELANBIDE11_CONTRATACION
--------------------------------------------------------
  ALTER TABLE MELANBIDE11_CONTRATACION ADD CONSTRAINT MELANBIDE11_CONTRATACION_PK PRIMARY KEY (ID) USING INDEX  ENABLE;
  ALTER TABLE MELANBIDE11_CONTRATACION MODIFY (ID NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Sequence SEQ_MELANBIDE11_CONTRATACION
--------------------------------------------------------
   CREATE SEQUENCE  SEQ_MELANBIDE11_CONTRATACION  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Table MELANBIDE11_SUBSOLIC
--------------------------------------------------------
  CREATE TABLE MELANBIDE11_SUBSOLIC 
   (	ID NUMBER(8,0), 
	NUM_EXP VARCHAR2(30 BYTE), 
	ESTADO VARCHAR2(1 BYTE), 
	ORGANISMO VARCHAR2(150 BYTE), 
	OBJETO VARCHAR2(200 BYTE), 
	IMPORTE NUMBER(8,2), 
	FECHA DATE
   ) ;

	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.ID IS 'Id secuencial';
	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.NUM_EXP IS 'Número de Expediente';
	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.ESTADO IS 'Estado de la Ayuda';
	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.ORGANISMO IS 'Organismo concedente';
	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.OBJETO IS 'Descripción objeto de la ayuda';
	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.IMPORTE IS 'Importe  de la ayuda';
	COMMENT ON COLUMN MELANBIDE11_SUBSOLIC.FECHA IS 'Fecha Solicitud o Concesión';
	
--------------------------------------------------------
--  DDL for Index MELANBIDE11_SUBSOLIC_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX MELANBIDE11_SUBSOLIC_PK ON MELANBIDE11_SUBSOLIC (ID);

--------------------------------------------------------
--  Constraints for Table MELANBIDE11_SUBSOLIC
--------------------------------------------------------

  ALTER TABLE MELANBIDE11_SUBSOLIC MODIFY (ID NOT NULL ENABLE);
  ALTER TABLE MELANBIDE11_SUBSOLIC ADD CONSTRAINT MELANBIDE11_SUBSOLIC_PK PRIMARY KEY (ID) USING INDEX  ENABLE;

--------------------------------------------------------
--  DDL for Sequence SEQ_MELANBIDE11_SUBSOLIC
--------------------------------------------------------

   CREATE SEQUENCE  SEQ_MELANBIDE11_SUBSOLIC  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;